### ISSUE TITLE
Кластерная файловая система.

### ISSUE THREAD

**Issue by glomikuz** [glomikuz/slackers-team#5]
Нужно что  бы бвыло

**Comment by dabarabash** [comment]
Нужно, чтобы файлы, создаваемые на одном хосте в какой-то определенной папке - тут же были доступны на другом хосте.

**Comment by glomikuz** [comment]
#6

**Comment by glomikuz** [comment]
sdfgsdf

**Comment by glomikuz** [comment]
CLOSE
